apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clavis

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - control-plane.yaml
  - gateway.yaml
  - admin-portal.yaml
  - migrate-seed.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: clavis/control-plane
    newTag: latest
  - name: clavis/gateway
    newTag: latest
  - name: clavis/admin-portal
    newTag: latest
